#!/usr/bin/env node
/**
 * Copies the frontend's Angular-free pure modules into src/shared/ and records their
 * SHA-256 digests, so parity.spec.ts can fail the build when the two drift apart.
 *
 *   node scripts/sync-shared.mjs          copy + record digests
 *   node scripts/sync-shared.mjs --check   verify only, exit 1 on drift
 *
 * These files are the source of truth for the 7 statuses and their order (every *Rank
 * column derives from it), the 22 permission thresholds, the transition matrix,
 * REVERSE_RELATIONSHIP, the upload limits and the filter defaults. A silent divergence
 * would not fail a type-check — it would just quietly answer queries differently than
 * the UI does. Hence the digests.
 */
import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const backend = resolve(here, '..');
const source = resolve(backend, '../frontend/src/app/core');
const target = resolve(backend, 'src/shared');
const digestFile = join(target, '.digests.json');

/**
 * `to` differs from `from` only where the backend needs a different local name:
 * issue-filter.ts becomes filter-semantics.ts because only part of it applies here:
 * criteriaToParams/paramsToCriteria ARE the URL contract and are used in production, while
 * filterIssues/sortIssues are test-only — production filtering goes through SQL
 * (see issue-query.builder.ts), and the two are compared in test/integration/filter-parity.
 */
const FILES = [
  { from: 'models.ts', to: 'models.ts' },
  { from: 'config.ts', to: 'config.ts' },
  { from: 'rich.ts', to: 'rich.ts' },
  { from: 'metrics.ts', to: 'metrics.ts' },
  // The only copied file that does not survive our stricter compiler flags: the frontend
  // does not enable noUncheckedIndexedAccess, and seed.ts indexes arrays freely
  // (`projects[i % 7 === 0 ? 3 : ...]`, `SUMMARIES[(i * 7) % len]`). Editing it here would
  // break the byte-for-byte parity the digests guarantee, so it is exempted instead.
  // The other five keep full type checking, including config.ts's threshold table.
  { from: 'seed.ts', to: 'seed.ts', nocheck: true },
  { from: 'issue-filter.ts', to: 'filter-semantics.ts' },
];

const BANNER = (file) =>
  `// AUTO-GENERATED by scripts/sync-shared.mjs from frontend/src/app/core/${file.from}\n` +
  `// Do not edit here. Change the frontend file, then run: npm run sync:shared\n` +
  (file.nocheck
    ? `// @ts-nocheck -- verbatim copy; checked by the frontend build, pinned by .digests.json\n`
    : '');

/** Rewrites the frontend's intra-core imports onto the local (possibly renamed) files. */
function rewriteImports(code) {
  const map = new Map(FILES.map((f) => [f.from.replace(/\.ts$/, ''), f.to.replace(/\.ts$/, '')]));
  return code.replace(/(from\s+')\.\/([A-Za-z0-9._-]+)(')/g, (whole, pre, mod, post) => {
    const renamed = map.get(mod);
    return renamed ? `${pre}./${renamed}${post}` : whole;
  });
}

const sha = (s) => createHash('sha256').update(s, 'utf8').digest('hex');

const check = process.argv.includes('--check');
const digests = {};
const drift = [];

await mkdir(target, { recursive: true });

for (const file of FILES) {
  const original = await readFile(join(source, file.from), 'utf8');
  digests[file.from] = sha(original);

  if (!check) {
    await writeFile(join(target, file.to), BANNER(file) + rewriteImports(original), 'utf8');
    continue;
  }

  let recorded;
  try {
    recorded = JSON.parse(await readFile(digestFile, 'utf8'))[file.from];
  } catch {
    recorded = undefined;
  }
  if (recorded !== digests[file.from]) drift.push(file.from);
}

if (check) {
  if (drift.length) {
    console.error(
      `Shared modules have drifted from the frontend:\n` +
        drift.map((f) => `  frontend/src/app/core/${f}`).join('\n') +
        `\n\nRun: npm run sync:shared   (then re-run the tests)\n`,
    );
    process.exit(1);
  }
  console.log(`shared: ${FILES.length} files in sync`);
} else {
  await writeFile(digestFile, JSON.stringify(digests, null, 2) + '\n', 'utf8');
  console.log(`shared: copied ${FILES.length} files from ${source}`);
}
