// AUTO-GENERATED by scripts/sync-shared.mjs from frontend/src/app/core/seed.ts
// Do not edit here. Change the frontend file, then run: npm run sync:shared
// @ts-nocheck -- verbatim copy; checked by the frontend build, pinned by .digests.json
import { defaultPrefs, defaultWorkflow, STATUSES } from './config';
import type {
  AccessLevel, Comment, Db, HistoryEntry, Issue, Notification, Priority, Project, Reproducibility, Severity,
  Sprint, Status, User,
} from './models';
import { doc } from './rich';

export const SCHEMA_VERSION = 1;

function rng(seed: number) {
  return () => {
    seed |= 0;
    seed = (seed + 0x6d2b79f5) | 0;
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const DAY = 86_400_000;

export function createSeed(now = Date.now()): Db {
  const rand = rng(42);
  const pick = <T>(arr: readonly T[]): T => arr[Math.floor(rand() * arr.length)];
  const iso = (daysAgo: number) => new Date(now - daysAgo * DAY).toISOString();
  const day = (offset: number) => iso(-offset).slice(0, 10);
  let seq = 1000;
  const id = () => ++seq;

  const mkUser = (uid: number, username: string, realName: string, accessLevel: AccessLevel, color: string, enabled = true): User => ({
    id: uid, username, realName, email: `${username}@example.com`, accessLevel, enabled, avatarColor: color,
    prefs: defaultPrefs(), lastVisit: iso(1 + uid / 10), created: iso(400 - uid * 10),
  });
  const users: User[] = [
    mkUser(1, 'administrator', 'Alex Morgan', 90, '#3875d7'),
    mkUser(2, 'mlopez', 'María López', 70, '#c0662b'),
    mkUser(3, 'dkim', 'Daniel Kim', 55, '#2e8b57'),
    mkUser(4, 'srossi', 'Sofia Rossi', 55, '#8e44ad'),
    mkUser(5, 'loconnor', "Liam O'Connor", 55, '#b8860b'),
    mkUser(6, 'eschulz', 'Emma Schulz', 40, '#c0392b'),
    mkUser(7, 'nwilliams', 'Noah Williams', 25, '#16a085'),
    mkUser(8, 'cdubois', 'Chloé Dubois', 10, '#6d4c41', false),
  ];
  users[0].prefs.language = 'en';

  const members = (lvls: [number, AccessLevel][]) => lvls.map(([userId, accessLevel]) => ({ userId, accessLevel }));
  const cat = (name: string, defaultHandlerId: number | null = null) => ({ name, defaultHandlerId });
  const ver = (name: string, daysFromNow: number, released: boolean, description = '') =>
    ({ name, date: day(daysFromNow), released, obsolete: false, description });

  const projects: Project[] = [
    {
      id: 1, name: 'Web Portal', key: 'WEB', status: 'development', viewState: 'public', enabled: true, parentId: null,
      description: doc('Customer-facing web portal: account management, billing and support center.'),
      categories: [cat('UI', 4), cat('Backend API', 3), cat('Authentication', 3), cat('Performance', 5), cat('Documentation')],
      versions: [ver('1.0', -120, true, 'Initial launch'), ver('1.1', -45, true), ver('1.2', 20, false), ver('2.0', 90, false, 'Redesign')],
      members: members([[2, 70], [3, 55], [4, 55], [5, 55], [6, 40], [7, 25]]), customFieldIds: [1, 2, 3], created: iso(380),
    },
    {
      id: 2, name: 'Mobile App', key: 'MOB', status: 'release', viewState: 'public', enabled: true, parentId: null,
      description: doc('iOS and Android clients.'),
      categories: [cat('iOS', 5), cat('Android', 4), cat('Sync'), cat('Notifications')],
      versions: [ver('3.4', -30, true), ver('3.5', 14, false), ver('4.0', 75, false)],
      members: members([[2, 70], [4, 55], [5, 55], [7, 25]]), customFieldIds: [2], created: iso(300),
    },
    {
      id: 3, name: 'Data Platform', key: 'DATA', status: 'development', viewState: 'private', enabled: true, parentId: null,
      description: doc('Internal ETL pipelines, warehouse and reporting.'),
      categories: [cat('ETL', 3), cat('Warehouse'), cat('Reporting', 6)],
      versions: [ver('0.9', -20, true), ver('1.0', 40, false)],
      members: members([[2, 70], [3, 55], [6, 40]]), customFieldIds: [], created: iso(200),
    },
    {
      id: 4, name: 'Admin Console', key: 'ADM', status: 'development', viewState: 'public', enabled: true, parentId: 1,
      description: doc('Back-office console, subproject of Web Portal.'),
      categories: [cat('Settings'), cat('Permissions', 3)],
      versions: [ver('1.0', 30, false)],
      members: members([[2, 70], [3, 55]]), customFieldIds: [], created: iso(150),
    },
  ];

  const sprints: Sprint[] = [
    { id: 1, projectId: 1, name: 'Sprint 21', goal: 'Stabilize billing', start: day(-35), end: day(-21), state: 'closed', capacity: 30 },
    { id: 2, projectId: 1, name: 'Sprint 22', goal: 'Account settings revamp', start: day(-7), end: day(7), state: 'active', capacity: 34 },
    { id: 3, projectId: 1, name: 'Sprint 23', goal: 'Performance', start: day(8), end: day(21), state: 'planned', capacity: 30 },
    { id: 4, projectId: 2, name: 'Sprint 8', goal: 'Offline sync', start: day(-28), end: day(-14), state: 'closed', capacity: 20 },
    { id: 5, projectId: 2, name: 'Sprint 9', goal: 'Push notifications', start: day(-4), end: day(10), state: 'active', capacity: 24 },
    { id: 6, projectId: 3, name: 'Sprint 3', goal: 'Nightly ETL reliability', start: day(-10), end: day(4), state: 'active', capacity: 18 },
  ];

  const SUMMARIES = [
    'Login button unresponsive on Safari', 'Password reset email never arrives', 'Dashboard loads slowly with 1k+ items',
    'Typo in the invoice footer', 'Crash when uploading a PNG larger than 5 MB', 'Session expires too early',
    'Add dark mode to settings page', 'API returns 500 on empty payload', 'Pagination skips the last page',
    'Date picker shows wrong week start', 'Export to CSV misses custom fields', 'Notifications duplicated after reconnect',
    'Offline changes lost after app update', 'Search ignores accented characters', 'Avatar upload rotates photos',
    'Memory leak in the report viewer', 'Two-factor code field rejects paste', 'Tooltip overlaps dropdown menu',
    'Deadlock in nightly ETL job', 'Warehouse partitions not pruned', 'Charts render blank on first load',
    'Improve error message for expired token', 'Support SSO with Azure AD', 'Rate limiter blocks legitimate users',
    'Wrong currency symbol for CHF', 'Scroll position resets on back navigation', 'Keyboard navigation missing in grid',
    'Push notification opens wrong screen', 'Sync conflict dialog appears twice', 'Upgrade charting library',
    'Audit log does not record role changes', 'Permissions page freezes with many roles', 'Broken link in onboarding docs',
    'Font rendering blurry on Windows', 'Add bulk edit for tickets', 'Timezone mismatch in scheduled reports',
    'Android back button closes the app', 'iOS widget shows stale data', 'Increase test coverage for billing', 'Migrate cron jobs to scheduler',
  ];
  const TAGS = ['regression', 'ux', 'security', 'customer', 'quick-win', 'tech-debt', 'backend', 'frontend'];
  const PLATFORMS = ['Desktop', 'Mobile', 'Tablet', 'Server'];
  const OSES = ['Windows 11', 'macOS 15', 'Ubuntu 24.04', 'iOS 19', 'Android 16'];
  const PRIOS: Priority[] = ['low', 'normal', 'normal', 'normal', 'high', 'high', 'urgent', 'immediate', 'none'];
  const SEVS: Severity[] = ['minor', 'minor', 'major', 'major', 'crash', 'block', 'feature', 'feature', 'tweak', 'text', 'trivial'];
  const REPRO: Reproducibility[] = ['always', 'always', 'sometimes', 'random', 'have_not_tried', 'na'];
  const STATUS_POOL: Status[] = ['new', 'new', 'feedback', 'acknowledged', 'confirmed', 'assigned', 'assigned', 'assigned', 'resolved', 'resolved', 'closed', 'closed'];
  const devs = [3, 4, 5, 6];

  const issues: Issue[] = [];
  const comments: Comment[] = [];
  const history: HistoryEntry[] = [];
  const hist = (issueId: number, userId: number, date: string, type: HistoryEntry['type'], field = '', o = '', n = '') =>
    history.push({ id: id(), issueId, userId, date, type, field, old: o, new: n });

  const NOTE_TEXTS = [
    'I can reproduce this on the staging environment.', 'Could you attach the browser console log?',
    'Fixed in the latest build, please verify.', 'This looks related to the recent caching change.',
    'Customer reported it again this morning.', 'Workaround: clear the local cache and retry.',
    'Needs product decision before we continue.', 'Added a regression test.',
  ];

  for (let i = 1; i <= 80; i++) {
    const project = projects[i % 7 === 0 ? 3 : i % 5 === 0 ? 2 : i % 3 === 0 ? 1 : 0];
    const status = pick(STATUS_POOL);
    let createdAgo = Math.floor(rand() * 90) + 1;
    let updatedAgo = Math.max(0, createdAgo - Math.floor(rand() * createdAgo));
    const handlerId = status === 'new' && rand() < 0.6 ? null : pick(devs);
    const reporterId = pick([2, 3, 4, 6, 7, 7, 7]);
    const category = pick(project.categories).name;
    const projSprints = sprints.filter((s) => s.projectId === project.id);
    const sprint = projSprints.length && rand() < 0.65 ? pick(projSprints) : null;
    const resolved = status === 'resolved' || status === 'closed';
    if (sprint && resolved) {
      // Resolve sprint issues inside the sprint window so burndowns look realistic.
      const startAgo = (now - Date.parse(sprint.start)) / DAY;
      const endAgo = Math.max(0.2, (now - Date.parse(sprint.end)) / DAY);
      if (startAgo > endAgo) {
        updatedAgo = endAgo + rand() * (startAgo - endAgo);
        createdAgo = Math.max(createdAgo, Math.ceil(startAgo) + 1);
      }
    }
    const openVersions = project.versions.filter((v) => !v.released);
    const target = rand() < 0.7 ? pick(project.versions).name : '';
    const issue: Issue = {
      id: i, projectId: project.id,
      sprintId: sprint?.id ?? null,
      category, summary: SUMMARIES[(i * 7) % SUMMARIES.length],
      description: doc(
        'When performing the action described in the summary, the system does not behave as expected.',
        'Expected: the operation completes successfully. Actual: it fails or behaves inconsistently.',
      ),
      stepsToReproduce: rand() < 0.6 ? doc('1. Log in as a regular user', '2. Navigate to the affected screen', '3. Perform the action') : null,
      additionalInfo: rand() < 0.3 ? doc('Seen in production logs since the last deployment.') : null,
      status, resolution: resolved ? pick(['fixed', 'fixed', 'fixed', 'wont_fix', 'duplicate', 'unable_to_reproduce'] as const) : 'open',
      priority: pick(PRIOS), severity: pick(SEVS), reproducibility: pick(REPRO),
      platform: pick(PLATFORMS), os: pick(OSES), osBuild: '', productVersion: pick(project.versions).name,
      targetVersion: target, fixedInVersion: resolved && target ? target : '',
      reporterId, handlerId, viewState: rand() < 0.1 ? 'private' : 'public', sticky: i === 3,
      tags: TAGS.filter(() => rand() < 0.15),
      monitorIds: [...new Set([reporterId, ...(handlerId ? [handlerId] : [])])],
      relationships: [],
      dueDate: !resolved && rand() < 0.35 ? day(Math.floor(rand() * 30) - 8) : null,
      estimate: rand() < 0.5 ? Math.ceil(rand() * 16) : null,
      storyPoints: rand() < 0.7 ? pick([1, 2, 3, 5, 8, 13]) : null,
      customFields: project.id === 1 && rand() < 0.5 ? { 1: pick(['Chrome', 'Firefox', 'Safari', 'Edge']), 3: rand() < 0.3 ? '1' : '' } : {},
      created: iso(createdAgo), updated: iso(updatedAgo),
    };
    if (issue.sprintId === null && openVersions.length === 0) issue.targetVersion = '';
    issues.push(issue);

    hist(i, reporterId, issue.created, 'created');
    if (handlerId) hist(i, 2, iso(createdAgo - 0.1), 'field', 'handlerId', '', String(handlerId));
    if (status !== 'new') {
      const path = STATUSES.slice(0, STATUSES.indexOf(status) + 1).filter((s) => s === 'new' || s === status || rand() < 0.3);
      for (let k = 1; k < path.length; k++) {
        hist(i, handlerId ?? 2, iso(createdAgo - (createdAgo - updatedAgo) * (k / (path.length - 1))), 'field', 'status', path[k - 1], path[k]);
      }
      if (resolved) hist(i, handlerId ?? 2, issue.updated, 'field', 'resolution', 'open', issue.resolution);
    }

    const noteCount = Math.floor(rand() * 4);
    for (let n = 0; n < noteCount; n++) {
      const authorId = pick([reporterId, handlerId ?? 2, 2]);
      const created = iso(createdAgo - (createdAgo - updatedAgo) * ((n + 1) / (noteCount + 1)));
      const mentionTarget = rand() < 0.3 ? users.find((u) => u.id === pick(devs))! : null;
      const body = doc(pick(NOTE_TEXTS));
      if (mentionTarget) {
        body.content![0].content!.unshift(
          { type: 'mention', attrs: { id: String(mentionTarget.id), label: mentionTarget.username } },
          { type: 'text', text: ' ' },
        );
      }
      const c: Comment = {
        id: id(), issueId: i, authorId, body, private: rand() < 0.1,
        timeSpent: rand() < 0.4 ? pick([15, 30, 45, 60, 90, 120]) : 0, created, edited: null,
      };
      comments.push(c);
      hist(i, authorId, created, 'note_added', 'note', '', String(c.id));
    }
  }

  // A few relationships (kept symmetric).
  const link = (a: number, type: Issue['relationships'][number]['type'], b: number, rev: Issue['relationships'][number]['type']) => {
    issues[a - 1].relationships.push({ type, issueId: b });
    issues[b - 1].relationships.push({ type: rev, issueId: a });
  };
  link(2, 'related_to', 6, 'related_to');
  link(12, 'duplicate_of', 29, 'has_duplicate');
  link(1, 'parent_of', 4, 'child_of');
  link(1, 'parent_of', 8, 'child_of');

  const notifications: Notification[] = issues
    .filter((x) => x.handlerId === 3)
    .slice(0, 6)
    .map((x, k) => ({
      id: id(), userId: 3, issueId: x.id, actorId: 2, type: k % 2 ? 'note' : 'assigned',
      text: x.summary, read: k > 2, date: x.updated,
    }));

  return {
    schema: SCHEMA_VERSION,
    seq,
    users, projects, sprints, issues, comments, history, notifications,
    attachments: [],
    filters: [
      { id: id(), name: 'My open high priority', ownerId: 3, shared: false, projectId: null, isDefault: false,
        criteria: { handlerIds: [-1], priorities: ['high', 'urgent', 'immediate'] }, columns: [], sort: [{ column: 'priority', dir: 'desc' }] },
      { id: id(), name: 'Unassigned bugs', ownerId: 2, shared: true, projectId: null, isDefault: false,
        criteria: { handlerIds: [0], severities: ['minor', 'major', 'crash', 'block'] }, columns: [], sort: [] },
      { id: id(), name: 'Overdue', ownerId: 1, shared: true, projectId: null, isDefault: false,
        criteria: { overdueOnly: true }, columns: [], sort: [{ column: 'dueDate', dir: 'asc' }] },
    ],
    customFields: [
      { id: 1, name: 'Browser', type: 'list', options: ['Chrome', 'Firefox', 'Safari', 'Edge'], required: false, defaultValue: '' },
      { id: 2, name: 'Customer', type: 'string', options: [], required: false, defaultValue: '' },
      { id: 3, name: 'Regression', type: 'checkbox', options: [], required: false, defaultValue: '' },
    ],
    workflow: defaultWorkflow(),
  };
}
